### PR TITLE
Turn on Flash on dark places

### PR DESCRIPTION
**Pull request by aadarshadhakalg**
Fixes for #5

### CODE REVIEW

**Comment by basnetsoyuj** [comment]
@aadarshadhakalg Hey, sorry I wasn't active for the past few days. This flash feature works very nicely, great job on that. Thank you so much for continuously contributing to Drishti!

I see that you've added `route_observer.dart` and `route_generator.dart` to pause and resume the Flash mode. I also noticed that the camera keeps running in the background (and so does the flash mode) when we switch to mobile's home screen.

So, instead of using `route_observer.dart` , I was wondering if we could use `didChangeAppLifecycleState` function of `CameraAppState`to detect changes (either `AppLifecycleState.resumed` or `AppLifecycleState.inactive` `AppLifecycleState.paused` ) and based on that use these logics there:
image

I think this might help handle cases more easily (both switching to other apps/home screen as well as other pages in Drishti)

**Comment by aadarshadhakalg** [comment]
@basnetsoyuj  I think ```didChangeAppLifecycleState``` will not be called when we navigate to a different page. So, I used navigator_observer and whenever the user leaves the camera page then I paused the flash stream and when the user gets back to the camera screen then resume it. 

And, for the camera running in the background, we can use ```didChangeAppLifecycleState```. I should have done that, I had not used the camera plugin before so I had no idea about that method. Anyway, I will look at what I can do.

**Comment by basnetsoyuj** [comment]
ah okay, gotcha. Would be nice if there was something that gets called when navigating to different pages. That way, the logic to turn flash off would be implemented in the `CameraAppState` Class itself. So later on, when we add more components, we wouldn't have to make any changes to the codebase. Just checked and found out that the `dispose()` function is also not called.

**Comment by aadarshadhakalg** [comment]
Yes, ```dispose``` is called if we  ```pop``` the previous page while navigating to another page. And what we can do is add WillPopScope to the next page and when a user tries to go back then we push the camera page again. I don't know it is a bad or good way but I am not fond of this approach.

**Comment by basnetsoyuj** [comment]
Yeah that seems messy, let's go with your initial approach

**Review by basnetsoyuj — APPROVED** [review]

**Comment by chhetri22** [comment]
Thanks for your contributions, @aadarshadhakalg!

**Pull request merged**
